# Generated by Django 4.2.2 on 2023-06-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_carrito_itemcarrito_producto_itemcarrito_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='carrito_relacionado',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='producto_imagenes'),
        ),
    ]
