# Generated by Django 4.2.2 on 2023-06-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_remove_producto_carrito_relacionado_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='description',
        ),
        migrations.AddField(
            model_name='animal',
            name='descripcion',
            field=models.CharField(default='valor_predeterminado', max_length=200),
        ),
    ]
